name: cats_app
description: Prueba tecnica para la empresa Pragma
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_launcher_icons: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/splash/

flutter_native_splash: # flutter pub run flutter_native_splash:create
  image: assets/splash/splash_ico.png
  color: "#030A1A"
  android: true
  ios: true
  web: true

flutter_icons: # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash/splash_ico.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A0A0A"
  web:
    generate: true
    image_path: "assets/splash/splash_ico.png"
    background_color: "#030A1A"
    theme_color: "#030A1A"
